SocialNetwork/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using SocialNetwork.Core.Application.ViewModels.User;
using SocialNetwork.Core.Application.Helpers;
using SocialNetwork.Core.Application.Dtos.Account;
using SocialNetwork.Core.Application.Interfaces.Services;

namespace SocialNetwork.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly AuthenticationResponse userViewModel;
        private readonly IUserService _userService;

        public ProfileController(IHttpContextAccessor httpContextAccessor, IUserService userService)
        {
            _httpContextAccessor = httpContextAccessor;
            _userService = userService;
            userViewModel = _httpContextAccessor.HttpContext.Session.Get<AuthenticationResponse>("user");
        }

        public async Task<IActionResult> Edit()
        {
            SaveUserViewModel vm = await _userService.GetByIdAsync(userViewModel.Id);
            return View("Edit", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SaveUserViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            SaveUserViewModel userVm = await _userService.GetByIdAsync(userViewModel.Id);
            if (userVm.HasError)
            {
                vm.HasError = userVm.HasError;
                vm.Error = userVm.Error;
                return View(vm);
            }

            vm.ProfilePicture = UploadFilesHelper.UploadFile(vm.File, vm.Id, "Posts", true, userVm.ProfilePicture);
            await _userService.UpdateAsync(vm, userVm.Id);

            return RedirectToRoute(new { controller = "Home", action = "Index" });
        }
    }
}

SocialNetwork/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using SocialNetwork.Core.Application.Dtos.Account
@using SocialNetwork.Core.Application.Helpers;
@using SocialNetwork.Core.Application.ViewModels.User;
@inject IHttpContextAccessor httpContextAccessor;
@{
    var User = httpContextAccessor.HttpContext.Session.Get<AuthenticationResponse>("user");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SocialNetwork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SocialNetwork.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold fs-4" asp-area="" asp-controller="@(User != null ? "Home" : "User")" asp-action="@(User != null ? "Index" : "Login")">SocialNetwork</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User != null)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friends</a>
                            </li>
                        </ul>
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle text-decoration-none text-black" href="#" id="userDropdown" role="button"
                               data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="d-none d-lg-inline">@User.Username</span>
                                <img src="@User.ProfilePicture" class="rounded-circle" alt="Profile picture"
                                     style="width: 25px; height: 25px; margin-left 10px;">
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                <a class="dropdown-item small" asp-area="" asp-controller="Profile" asp-action="Edit">
                                    <i class="bi bi-person-lines-fill me-1 text-muted"></i>
                                    My Profile
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item small" asp-area="" asp-controller="User" asp-action="LogOut">
                                    <i class="bi bi-box-arrow-right me-1 text-muted"></i>
                                    Logout
                                </a>
                            </ul>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SocialNetwork - Made by <a href="https://github.com/AleGxrcia" target="_blank">AleGxrcia</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>